services:
  server:
    image: kingdoms
    ports:
      - "8080:8080"
    environment:
      DB_PASS: example
      DJANGO_SUPERUSER_PASSWORD: dev
      DJANGO_SETTINGS_MODULE: conf.settings.dev
      DJANGO_SECRET_KEY: testkey
    volumes: 
      - ./website/build/static/:/app/build/static/
      - dbdata:/etc/postgresql/15/kingdoms/
volumes:
  dbdata:
