services:
  server:
    image: kingdoms
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_PASS: 2GJbU_fsfR7B7hbibe7NJQ
      DB_NAME: test
      DB_USER: test
      DB_HOST: kingdoms-supply-3902.jxf.gcp-us-west2.cockroachlabs.cloud
      DB_PORT: 26257
      DJANGO_SETTINGS_MODULE: conf.settings.prod
      DJANGO_SECRET_KEY: testkey
      DJANGO_SUPERUSER_PASSWORD: dev
      MAILJET_USERNAME: ac93bc999df2a520c17f86dd773a1073
      MAILJET_PASS: 0c7f6114558624b9e57c6589858b5c2a
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - ./website/build/:/app/build/
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres
      POSTGRES_DB: supply
    volumes:
      - pgdata:/var/lib/postgresql/data 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 10
volumes:
  pgdata:
