# Generated by Django 2.2.10 on 2020-10-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='landscape',
            field=models.BooleanField(default=False),
        ),
    ]
