# Generated by Django 2.2.10 on 2020-10-02 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_card_landscape'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True),
        ),
    ]
