# Generated by Django 2.2.10 on 2020-10-22 09:35

import api.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_kingdom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kingdom',
            name='cards',
        ),
        migrations.AddField(
            model_name='kingdom',
            name='landscapes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100, validators=[api.models.validate_card_exists]), default=list, size=None),
        ),
        migrations.AddField(
            model_name='kingdom',
            name='supply',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100, validators=[api.models.validate_card_exists]), default=list, size=None),
        ),
    ]
