# Generated by Django 2.2.10 on 2020-11-29 11:42

import api.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20201023_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kingdom',
            name='landscapes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100, validators=[api.models.validate_card_exists]), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='kingdom',
            name='supply',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100, validators=[api.models.validate_card_exists]), blank=True, default=list, size=None),
        ),
    ]
