# Generated by Django 2.2.10 on 2021-01-24 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='kingdom',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kingdom',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
