# Generated by Django 2.2.10 on 2021-01-24 08:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210124_0513'),
    ]

    operations = [
        migrations.AddField(
            model_name='kingdom',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
