# Generated by Django 2.2.10 on 2021-01-25 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_kingdom_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('accounts', models.IntegerField(default=0)),
                ('kingdoms', models.IntegerField(default=0)),
                ('published_kingdoms', models.IntegerField(default=0)),
            ],
        ),
    ]
