# Generated by Django 2.2.10 on 2021-02-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_metric_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kingdom',
            name='published',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
