# Generated by Django 2.2.10 on 2021-02-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20210204_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kingdom',
            name='score',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
